### ISSUE TITLE
Official solution doesn't pass the tests

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/rails-dynamic-request-lab#6]
Just a heads up about this: the difference is in the routes -- if you use 
get "students/:id", to: "students#show"
as it suggests, instead of 
  resources :students, only: [:index, :show]
end, 
the tests won't pass when "index" is missing. 

Also, the relationship between this session's lesson and the lab, isn't good. It's the start of rails, and there should be more explanation about routes, since this is a big change from Sinatra. The list of requirements should be clearer and more descriptive, again, because this is the beginning of Rails and things are very unclear. The lessons go over the big picture of RESTful conventions, which is great, but to improve the intro to Rails, definitely include more on the specifics of routing, and the new relationships of MVC. 

Thanks!

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#7 .  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
